# Site wide configuration

title: Apotheek Van Dijck
locale: en_US
description: apotheek van dijck / blog / info
logo: site-logo.png
search: true
url: http://www.apotheekvandijck.be

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: joeri van dijck
  avatar: bio-photo.jpg
  email: info@apotheekvandijck.be
  disqus-shortname:
  twitter: joeri10
  facebook: joeri.vandijck
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: joerivandijck
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: ApotheekVanDijckBree
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
